spring.application.name=api-gateway

server.port= 9000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-security-realm

# Exposes a human-friendly Swagger UI so developers can visually explore and test the REST APIs
# (browse endpoints, see request/response models, and try calls without Postman)
# so it changed the path from  http://<host>:<port>/swagger-ui/index.htmll  to => http://<host>:<port>/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

# Exposes the same API contract in raw OpenAPI JSON format so tools (Swagger UI, code generators,
# CI/CD validators, and gateways) can programmatically read the API definition
# so it changes from http://<host>:<port>/v3/api-docs to http://<service>:<port>/api-docs
springdoc.api-docs.path=/api-docs



# Swagger dropdown entry for Product Service
# Swagger UI fetches Product Service API spec from /aggregate/product-service/v3/api-docs
# Gateway forwards this to: http://localhost:8080/api-docs
springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs

# Swagger dropdown entry for Order Service
# Swagger UI fetches Order Service API spec from /aggregate/order-service/v3/api-docs
# Gateway forwards this to: http://localhost:8081/api-docs
springdoc.swagger-ui.urls[1].name=Order Service
springdoc.swagger-ui.urls[1].url=/aggregate/order-service/v3/api-docs

# Swagger dropdown entry for Inventory Service
# Swagger UI fetches Inventory Service API spec from /aggregate/inventory-service/v3/api-docs
# Gateway forwards this to: http://localhost:8082/api-docs
springdoc.swagger-ui.urls[2].name=Inventory Service
springdoc.swagger-ui.urls[2].url=/aggregate/inventory-service/v3/api-docs
