services:
  product:
    base-url: http://localhost:8080
  order:
    base-url: http://localhost:8081
  inventory:
    base-url: http://localhost:8082

server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:


            # ===================================================================================================
            # =============== Product Service Configuration ===============
            # ===================================================================================================

            # Product API:
            # Client calls:   /api/product/**
            # Gateway forwards to: http://localhost:8080/api/product/**
            - id: product_service
              uri: ${services.product.base-url}
              predicates:
                - Path=/api/product/**
              filters:
                # Circuit breaker for Product Service:
                # - Monitors failures/timeouts when calling Product Service
                # - Opens the circuit if the service becomes unhealthy
                # - Forwards requests to /fallbackRoute when open
                #
                # We define this per service so each downstream dependency is isolated:
                # a failure in Product Service does not affect Order or Inventory routing.
                - name: CircuitBreaker  # This tells Spring Cloud Gateway CircuitBreaker filter factory to apply.
                  args:
                    id: productServiceCircuitBreaker  # Logical name of the Resilience4j circuit breaker instance
                    fallbackUri: forward:/fallbackRoute

            # -----------------------
            # Product Swagger:
            # -----------------------


            # Product Swagger:
            # Client calls:   /aggregate/product-service/v3/api-docs
            # Gateway forwards to: http://localhost:8080/api-docs
            - id: product_service_swagger
              uri: ${services.product.base-url}
              predicates:
                - Path=/aggregate/product-service/v3/api-docs
              filters:
                - SetPath=/api-docs
                # Circuit breaker for Product Service swagger:
                # - Monitors failures/timeouts when calling Product Service swagger
                # - Opens the circuit if the service becomes unhealthy
                # - Forwards requests to /fallbackRoute when open
                #
                # We define this per service so each downstream dependency is isolated:
                - name: CircuitBreaker  # This tells Spring Cloud Gateway CircuitBreaker filter factory to apply.
                  args:
                    id: productServiceSwaggerCircuitBreaker  # Logical name of the Resilience4j circuit breaker instance
                    fallbackUri: forward:/fallbackRoute


            # ===================================================================================================
            # =============== Order  Service Configuration ===============
            # ===================================================================================================

            # -----------------------
            # Order API:
            # -----------------------

            # Order API:
            # Client calls:   /api/order/**
            # Gateway forwards to: http://localhost:8081/api/order/**
            - id: order_service
              uri: ${services.order.base-url}
              predicates:
                - Path=/api/order/**
              filters:
                # Circuit breaker for Order Service:
                # - Monitors failures/timeouts when calling Order Service
                # - Opens the circuit if the service becomes unhealthy
                # - Forwards requests to /fallbackRoute when open
                #
                # Defined separately so Order Service failures do not cascade
                # into Product or Inventory routing.
                - name: CircuitBreaker # This tells Spring Cloud Gateway CircuitBreaker filter factory to apply.
                  args:
                    id: orderServiceCircuitBreaker  # Logical name of the Resilience4j circuit breaker instance
                    fallbackUri: forward:/fallbackRoute

            # -----------------------
            # Order Swagger:
            # -----------------------

            # Order Swagger:
            # Client calls:   /aggregate/order-service/v3/api-docs
            # Gateway forwards to: http://localhost:8081/api-docs
            - id: order_service_swagger
              uri: ${services.order.base-url}
              predicates:
                - Path=/aggregate/order-service/v3/api-docs
              filters:
                - SetPath=/api-docs
                # Circuit breaker for Order Service swagger:
                # - Monitors failures/timeouts when calling Order Service swagger
                # - Opens the circuit if the service becomes unhealthy
                # - Forwards requests to /fallbackRoute when open
                #
                # We define this per service so each downstream dependency is isolated:
                - name: CircuitBreaker  # This tells Spring Cloud Gateway CircuitBreaker filter factory to apply.
                  args:
                    id: orderServiceSwaggerCircuitBreaker  # Logical name of the Resilience4j circuit breaker instance
                    fallbackUri: forward:/fallbackRoute


            # ===================================================================================================
            # =============== Inventory   Service Configuration ===============
            # ===================================================================================================

            # -----------------------
            # Inventory API:
            # -----------------------

            # Inventory API:
            # Client calls:   /api/inventory/**
            # Gateway forwards to: http://localhost:8082/api/inventory/**
            - id: inventory_service
              uri: ${services.inventory.base-url}
              predicates:
                - Path=/api/inventory/**
              filters:
                # Circuit breaker for Inventory Service:
                # - Monitors failures/timeouts when calling Inventory Service
                # - Opens the circuit if the service becomes unhealthy
                # - Forwards requests to /fallbackRoute when open
                #
                # Kept separate so Inventory outages do not impact
                # Product or Order availability.
                - name: CircuitBreaker # This tells Spring Cloud Gateway CircuitBreaker filter factory to apply.
                  args:
                    id: inventoryServiceCircuitBreaker  # Logical name of the Resilience4j circuit breaker instance
                    fallbackUri: forward:/fallbackRoute

            # -----------------------
            # Inventory Swagger:
            # -----------------------

            # Inventory Swagger:
            # Client calls:   /aggregate/inventory-service/v3/api-docs
            # Gateway forwards to: http://localhost:8082/api-docs
            - id: inventory_service_swagger
              uri: ${services.inventory.base-url}
              predicates:
                - Path=/aggregate/inventory-service/v3/api-docs
              filters:
                - SetPath=/api-docs
                # Circuit breaker for Inventory Service swagger:
                # - Monitors failures/timeouts when calling Inventory Service
                # - Opens the circuit if the service becomes unhealthy
                # - Forwards requests to /fallbackRoute when open
                #
                # We define this per service so each downstream dependency is isolated:
                - name: CircuitBreaker  # This tells Spring Cloud Gateway CircuitBreaker filter factory to apply.
                  args:
                    id: inventoryServiceSwaggerCircuitBreaker  # Logical name of the Resilience4j circuit breaker instance
                    fallbackUri: forward:/fallbackRoute

            # ============================================================
            # ===================== Fallback Handling ====================
            # ============================================================

            # Fallback Route:
            # This route is used when any downstream service is unavailable or a circuit breaker is open.
            # Requests are internally forwarded here and a 503 (Service Unavailable) status is returned.

            - id: fallback_route
              uri: no://op   # "no://op" means "no operation,The gateway will NOT forward this request to any downstream service.This route exists only to generate a synthetic response inside the gateway.
              predicates:
                - Path=/fallbackRoute
              filters:
                - SetStatus=503
                - AddResponseHeader=Content-Type,application/json
                - AddResponseHeader=Fallback-Reason,ServiceUnavailable
